### ISSUE TITLE
NameError: global name 're' is not defined

### ISSUE THREAD

**Issue by ricortiz** [fedorov/MultiVolumeImporter#10]
I am seeing this error when building against Slicer/Slicer@36eaeaff5917ecb36e38867f7e2dde0615355cd0

Adding the following to MultiVolumeImporter.py solves the issue:

```
import re
```
Here is the entire error:

Traceback (most recent call last):
  File "/home/rortiz/Projects/NIRViewSlicer/build/S-bld/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/MultiVolumeImporter.py", line 189, in onImportButtonClicked
    self.humanSort(fileNames)
  File "/home/rortiz/Projects/NIRViewSlicer/build/S-bld/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/MultiVolumeImporter.py", line 155, in humanSort
    l.sort( key=alphanum_key )
  File "/home/rortiz/Projects/NIRViewSlicer/build/S-bld/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/MultiVolumeImporter.py", line 154, in <lambda>
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
NameError: global name 're' is not defined

**Comment by fedorov** [comment]
Thank you for reporting this. Fixed in https://github.com/fedorov/MultiVolumeImporter/commit/7741251bfc8c9229a0fc02aaf7b12d1326c13091, Slicer updated in r24063.

**Comment by jcfr** [comment]
@fedorov  @ricortiz  Thanks for working on this.

This was most likely a side effect of 738a74a9a
