### ISSUE TITLE
Integrate DSC support and make sure existing types are not broken

### ISSUE THREAD

**Issue by fedorov** [fedorov/MultiVolumeImporter#12]
By the way, I also did some tests on sample data of DCE, 4D Trace, QIN prostate T1 mapping, QIBA T1 mapping phantom and MGH T1 mapping.
It also works for DCE, 4D Trace, QIN prostate T1 mapping and MGH T1 mapping.
However, it might have some small issues when I tried to load QIBA T1 mapping phantom data (attached). The err message is
***
Traceback (most recent call last):
File "C:\Program Files\Slicer 4.4.0-2015-05-15\lib\Slicer-4.4\qt-scripted-modules\DICOMLib\DICOMWidgets.py", line 708, in loadCheckedLoadables
self.proceedWithReferencedLoadablesSelection()
File "C:\Program Files\Slicer 4.4.0-2015-05-15\lib\Slicer-4.4\qt-scripted-modules\DICOMLib\DICOMWidgets.py", line 751, in proceedWithReferencedLoadablesSelection
if not plugin.load(loadable):
File "C:/Program Files/Slicer 4.4.0-2015-05-15/lib/Slicer-4.4/qt-scripted-modules/MultiVolumeImporterPlugin.py", line 397, in load
mvImageArray.T[frameNumber] = frameImageArray
ValueError: setting an array element with a sequence.
***
As a result the status bar of loading images cannot reach 100%.  But the result was correct. One of the volume was loaded as multi-volume data.

**Comment by fedorov** [comment]
Resolved in the commits around the early Jan 2016 time frame ...
